/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EnRouteImport } from './routes/en'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RuRouteImport } from './routes/ru'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UzRouteImport } from './routes/uz'
import { Route as CategoriesIdRouteImport } from './routes/categories.$id'
import { Route as RuAboutRouteImport } from './routes/ru_.about'
import { Route as RuContactRouteImport } from './routes/ru_.contact'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as ToolsSlugRouteImport } from './routes/tools/$slug'
import { Route as UzAboutRouteImport } from './routes/uz_.about'
import { Route as UzContactRouteImport } from './routes/uz_.contact'
import { Route as RuToolsCurrencyRatesRouteImport } from './routes/ru_.tools.currency-rates'
import { Route as UzToolsCurrencyRatesRouteImport } from './routes/uz_.tools.currency-rates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RuRoute = RuRouteImport.update({
  id: '/ru',
  path: '/ru',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UzRoute = UzRouteImport.update({
  id: '/uz',
  path: '/uz',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIdRoute = CategoriesIdRouteImport.update({
  id: '/categories/$id',
  path: '/categories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RuAboutRoute = RuAboutRouteImport.update({
  id: '/ru_/about',
  path: '/ru/about',
  getParentRoute: () => rootRouteImport,
} as any)
const RuContactRoute = RuContactRouteImport.update({
  id: '/ru_/contact',
  path: '/ru/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/tools/$slug',
  path: '/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UzAboutRoute = UzAboutRouteImport.update({
  id: '/uz_/about',
  path: '/uz/about',
  getParentRoute: () => rootRouteImport,
} as any)
const UzContactRoute = UzContactRouteImport.update({
  id: '/uz_/contact',
  path: '/uz/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const RuToolsCurrencyRatesRoute = RuToolsCurrencyRatesRouteImport.update({
  id: '/ru_/tools/currency-rates',
  path: '/ru/tools/currency-rates',
  getParentRoute: () => rootRouteImport,
} as any)
const UzToolsCurrencyRatesRoute = UzToolsCurrencyRatesRouteImport.update({
  id: '/uz_/tools/currency-rates',
  path: '/uz/tools/currency-rates',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/en': typeof EnRoute
  '/favorites': typeof FavoritesRoute
  '/history': typeof HistoryRoute
  '/privacy': typeof PrivacyRoute
  '/ru': typeof RuRoute
  '/terms': typeof TermsRoute
  '/uz': typeof UzRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/ru/about': typeof RuAboutRoute
  '/ru/contact': typeof RuContactRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/uz/about': typeof UzAboutRoute
  '/uz/contact': typeof UzContactRoute
  '/tools/': typeof ToolsIndexRoute
  '/ru/tools/currency-rates': typeof RuToolsCurrencyRatesRoute
  '/uz/tools/currency-rates': typeof UzToolsCurrencyRatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/en': typeof EnRoute
  '/favorites': typeof FavoritesRoute
  '/history': typeof HistoryRoute
  '/privacy': typeof PrivacyRoute
  '/ru': typeof RuRoute
  '/terms': typeof TermsRoute
  '/uz': typeof UzRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/ru/about': typeof RuAboutRoute
  '/ru/contact': typeof RuContactRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/uz/about': typeof UzAboutRoute
  '/uz/contact': typeof UzContactRoute
  '/tools': typeof ToolsIndexRoute
  '/ru/tools/currency-rates': typeof RuToolsCurrencyRatesRoute
  '/uz/tools/currency-rates': typeof UzToolsCurrencyRatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/en': typeof EnRoute
  '/favorites': typeof FavoritesRoute
  '/history': typeof HistoryRoute
  '/privacy': typeof PrivacyRoute
  '/ru': typeof RuRoute
  '/terms': typeof TermsRoute
  '/uz': typeof UzRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/ru_/about': typeof RuAboutRoute
  '/ru_/contact': typeof RuContactRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/uz_/about': typeof UzAboutRoute
  '/uz_/contact': typeof UzContactRoute
  '/tools/': typeof ToolsIndexRoute
  '/ru_/tools/currency-rates': typeof RuToolsCurrencyRatesRoute
  '/uz_/tools/currency-rates': typeof UzToolsCurrencyRatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/en'
    | '/favorites'
    | '/history'
    | '/privacy'
    | '/ru'
    | '/terms'
    | '/uz'
    | '/categories/$id'
    | '/ru/about'
    | '/ru/contact'
    | '/tools/$slug'
    | '/uz/about'
    | '/uz/contact'
    | '/tools/'
    | '/ru/tools/currency-rates'
    | '/uz/tools/currency-rates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/en'
    | '/favorites'
    | '/history'
    | '/privacy'
    | '/ru'
    | '/terms'
    | '/uz'
    | '/categories/$id'
    | '/ru/about'
    | '/ru/contact'
    | '/tools/$slug'
    | '/uz/about'
    | '/uz/contact'
    | '/tools'
    | '/ru/tools/currency-rates'
    | '/uz/tools/currency-rates'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/en'
    | '/favorites'
    | '/history'
    | '/privacy'
    | '/ru'
    | '/terms'
    | '/uz'
    | '/categories/$id'
    | '/ru_/about'
    | '/ru_/contact'
    | '/tools/$slug'
    | '/uz_/about'
    | '/uz_/contact'
    | '/tools/'
    | '/ru_/tools/currency-rates'
    | '/uz_/tools/currency-rates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EnRoute: typeof EnRoute
  FavoritesRoute: typeof FavoritesRoute
  HistoryRoute: typeof HistoryRoute
  PrivacyRoute: typeof PrivacyRoute
  RuRoute: typeof RuRoute
  TermsRoute: typeof TermsRoute
  UzRoute: typeof UzRoute
  CategoriesIdRoute: typeof CategoriesIdRoute
  RuAboutRoute: typeof RuAboutRoute
  RuContactRoute: typeof RuContactRoute
  ToolsSlugRoute: typeof ToolsSlugRoute
  UzAboutRoute: typeof UzAboutRoute
  UzContactRoute: typeof UzContactRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  RuToolsCurrencyRatesRoute: typeof RuToolsCurrencyRatesRoute
  UzToolsCurrencyRatesRoute: typeof UzToolsCurrencyRatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru': {
      id: '/ru'
      path: '/ru'
      fullPath: '/ru'
      preLoaderRoute: typeof RuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uz': {
      id: '/uz'
      path: '/uz'
      fullPath: '/uz'
      preLoaderRoute: typeof UzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$id': {
      id: '/categories/$id'
      path: '/categories/$id'
      fullPath: '/categories/$id'
      preLoaderRoute: typeof CategoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru_/about': {
      id: '/ru_/about'
      path: '/ru/about'
      fullPath: '/ru/about'
      preLoaderRoute: typeof RuAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru_/contact': {
      id: '/ru_/contact'
      path: '/ru/contact'
      fullPath: '/ru/contact'
      preLoaderRoute: typeof RuContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/tools/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uz_/about': {
      id: '/uz_/about'
      path: '/uz/about'
      fullPath: '/uz/about'
      preLoaderRoute: typeof UzAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uz_/contact': {
      id: '/uz_/contact'
      path: '/uz/contact'
      fullPath: '/uz/contact'
      preLoaderRoute: typeof UzContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru_/tools/currency-rates': {
      id: '/ru_/tools/currency-rates'
      path: '/ru/tools/currency-rates'
      fullPath: '/ru/tools/currency-rates'
      preLoaderRoute: typeof RuToolsCurrencyRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uz_/tools/currency-rates': {
      id: '/uz_/tools/currency-rates'
      path: '/uz/tools/currency-rates'
      fullPath: '/uz/tools/currency-rates'
      preLoaderRoute: typeof UzToolsCurrencyRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EnRoute: EnRoute,
  FavoritesRoute: FavoritesRoute,
  HistoryRoute: HistoryRoute,
  PrivacyRoute: PrivacyRoute,
  RuRoute: RuRoute,
  TermsRoute: TermsRoute,
  UzRoute: UzRoute,
  CategoriesIdRoute: CategoriesIdRoute,
  RuAboutRoute: RuAboutRoute,
  RuContactRoute: RuContactRoute,
  ToolsSlugRoute: ToolsSlugRoute,
  UzAboutRoute: UzAboutRoute,
  UzContactRoute: UzContactRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  RuToolsCurrencyRatesRoute: RuToolsCurrencyRatesRoute,
  UzToolsCurrencyRatesRoute: UzToolsCurrencyRatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
